### PR TITLE
feat: Choose which settings to sync

### PR DESCRIPTION
**Pull request by Lisandra-dev**
- Edited settings to add a list for each profile
- Enabled profil will be in bold + have a star
- Added "play" button to enable profil 
- Added trash to delete profil from settings (it won't delete the folder in the targetPath. Dunno if it's a good idea to delete it?)
image

- Clicking on 'add profile' will open a modal. Checking if already existing profile throw an error.
- Added new interface per profile ; each file used by obsidian have their settings
- Enable/disable allow to keep different settings per profile in sync. 
	- If disabled: file won't be created in the profile folder, it will use the "already existing file" from Obsidian. Consequence:  sync (keep new version) will be disabled (as it always use the registered obsidian settings).
	- If enabled : File will be created and used when switching profile. Disabled file will be skipped.

Aka: allow to keep specific settings per profile. If I disable everything and keep only appeareance, I can have different appeareance for profile, but keeping the same obsidian hotkeys for all.

### CODE REVIEW

**Comment by 4Source** [comment]
Thanks for Committing but I already implemented it. Currently doing some bug fixes and testing.

**Comment by 4Source** [comment]
I just looked at your commit. I'll use some of your approaches and add them to my solution.

**Comment by 4Source** [comment]
See [dev](https://github.com/4Source/SettingsProfiles-Obsidian-Plugin/tree/dev) for current progress.

**Comment by Lisandra-dev** [comment]
As I only forked the main, I forgot to check the dev 😭
At last my works was useful!

**Comment by Lisandra-dev** [comment]
Real question : why do you prefer to use a suggest modal instead of a simple Modal with text Area for creating new profile?

**Comment by 4Source** [comment]
I just reused the existing Modal from the profileSwitcher due to time constraints. I am not opposed to use a simple modal. But I think it is don't effective if this modal just contain an input for the name. So if you like to implement such a modal I think it should contain all the SettingsProfile options exluding the enabeled this should only be affected by the switchProfile. May the ProfileConfigModal could be a base for this. If you like to implement it.

**Comment by Lisandra-dev** [comment]
I will do that with pleasure then ! 
So it won't implements the options for all file to enable ? Only the other settingsProfile option ?
Ie:
- autosync
- snippets
- name
?

I think `enabled` mean to the switch.

**Comment by 4Source** [comment]
Yes enable is used to switch the profile probably allow in the future multiple profiles but not Shure about that. 

I think the best is to load the settings from the current profile. But allow change all options there are available. Im SettingsConfigProfile is an example of how to automate the process.

**Pull request closed without merging**
